### ISSUE TITLE
Canplayer waiting response 

### ISSUE THREAD

**Issue by nico0481** [linux-can/can-utils#343]
Hello,

Do you think is is possible to implement canpalyer with conditionnal sending? 
I mean:
Having a candump log file, done with 'any' parameter as interface, on 2 canbus, using cangw for bridging.
My log file contains: 
Time stamp1 can0 xxxxxxx1 (xxx are Id and data)
Time stamp1 can1 yyyyyy1
Time stamp1 can0 xxxxxxx2
Time stamp1 can0 xxxxxxx3
Time stamp1 can1 yyyyyy2
...
...
...
...100's of lines

I would like to replay only "can0" frames (easy with canplayer) but waiting response from can1(contained in the log file)(and checking the correctness or only the ID) before sending the next can0 frames.
I've already tried replying only can0 frame, but seems to fail because of the timestamp an maybe reply from can1 are not synchronised.

I plan to test with some Python code, but not ready at the moment.

Thank you
Best regards
Nico

**Comment by hartkopp** [comment]
I assume you have to implement something new for this interactive behaviour.
For this use-case I (personally) would hack the canplayer so that it stops working whenever it should normally send something to can1. In this case the canplayer can perform a (blocking) read() from can1 (maybe through a separate CAN_RAW socket). If it get's a frame from can1 it continues working.
